/**
 * Test Fixtures - API Response Mocks
 *
 * Provides mock API responses for testing
 */
/**
 * Standard API response wrapper
 */
interface APIResponse<T> {
    success: boolean;
    data?: T;
    error?: {
        code: string;
        message: string;
    };
}
/**
 * Mock skills list response
 */
export declare const mockSkillsListResponse: APIResponse<any[]>;
/**
 * Mock single skill response
 */
export declare const mockSkillResponse: APIResponse<{
    content: string;
    metadata: any;
}>;
/**
 * Mock create skill response
 */
export declare const mockCreateSkillResponse: APIResponse<{
    name: string;
    path: string;
}>;
/**
 * Mock update skill response
 */
export declare const mockUpdateSkillResponse: APIResponse<{
    lastModified: number;
}>;
/**
 * Mock delete skill response
 */
export declare const mockDeleteSkillResponse: APIResponse<null>;
/**
 * Mock configuration response
 */
export declare const mockConfigResponse: APIResponse<any>;
/**
 * Mock private repos list response
 */
export declare const mockPrivateReposResponse: APIResponse<any[]>;
/**
 * Mock private repo skills response
 */
export declare const mockPrivateRepoSkillsResponse: APIResponse<any[]>;
/**
 * Mock Claude directories response
 */
export declare const mockClaudeDirectoriesResponse: APIResponse<string[]>;
/**
 * Error responses
 */
export declare const mockErrorResponse: APIResponse<never>;
export declare const mockAuthErrorResponse: APIResponse<never>;
export declare const mockNotFoundResponse: APIResponse<never>;
export declare const mockValidationErrorResponse: APIResponse<never>;
export declare const mockExternalModificationResponse: APIResponse<never>;
/**
 * AI generation responses
 */
export declare const mockAIStreamChunk = "---\nname: AI Generated Skill\ndescription: Generated by Claude\nversion: 1.0.0\n---\n\n# AI Generated Skill\n\nThis skill was generated by AI.\n";
/**
 * Search results response
 */
export declare const mockSearchResultsResponse: {
    results: {
        id: string;
        skillId: string;
        name: string;
        installs: number;
        source: string;
        description: string;
    }[];
    total: number;
    page: number;
};
/**
 * Create a mock response helper
 */
export declare function createMockResponse<T>(data: T, success?: boolean): APIResponse<T>;
/**
 * Create a mock error response helper
 */
export declare function createMockErrorResponse(code: string, message: string): APIResponse<never>;
export {};
//# sourceMappingURL=api-responses.d.ts.map