/**
 * Test Fixtures - API Response Mocks
 *
 * Provides mock API responses for testing
 */

/**
 * Standard API response wrapper
 */
interface APIResponse<T> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
  };
}

/**
 * Mock skills list response
 */
export const mockSkillsListResponse: APIResponse<any[]> = {
  success: true,
  data: [
    {
      name: 'Test Skill 1',
      path: '/skills/test-skill-1/skill.md',
      description: 'First test skill',
      lastModified: new Date().toISOString(),
      sourceMetadata: { type: 'local' },
    },
    {
      name: 'Test Skill 2',
      path: '/skills/test-skill-2/skill.md',
      description: 'Second test skill',
      lastModified: new Date().toISOString(),
      sourceMetadata: { type: 'registry', source: 'test-org/test-repo' },
    },
  ],
};

/**
 * Mock single skill response
 */
export const mockSkillResponse: APIResponse<{ content: string; metadata: any }> = {
  success: true,
  data: {
    content: `---
name: Test Skill
description: A test skill
version: 1.0.0
---

# Test Skill

Content here.
`,
    metadata: {
      lastModified: new Date().toISOString(),
      size: 100,
    },
  },
};

/**
 * Mock create skill response
 */
export const mockCreateSkillResponse: APIResponse<{ name: string; path: string }> = {
  success: true,
  data: {
    name: 'New Test Skill',
    path: '/skills/new-test-skill/skill.md',
  },
};

/**
 * Mock update skill response
 */
export const mockUpdateSkillResponse: APIResponse<{ lastModified: number }> = {
  success: true,
  data: {
    lastModified: Date.now(),
  },
};

/**
 * Mock delete skill response
 */
export const mockDeleteSkillResponse: APIResponse<null> = {
  success: true,
  data: null,
};

/**
 * Mock configuration response
 */
export const mockConfigResponse: APIResponse<any> = {
  success: true,
  data: {
    projectDirectories: ['/test/skills'],
    applicationSkillsDirectory: '/test/.skillsmn/skills',
    autoRefresh: true,
    skillEditorConfig: {
      fontSize: 14,
      theme: 'light',
      autoSaveEnabled: true,
      autoSaveDelay: 2000,
      showMinimap: false,
      lineNumbers: 'on',
      tabSize: 2,
      wordWrap: true,
    },
  },
};

/**
 * Mock private repos list response
 */
export const mockPrivateReposResponse: APIResponse<any[]> = {
  success: true,
  data: [
    {
      id: 'github-1',
      type: 'github',
      owner: 'test-org',
      repo: 'test-skills',
      displayName: 'test-org/test-skills',
    },
  ],
};

/**
 * Mock private repo skills response
 */
export const mockPrivateRepoSkillsResponse: APIResponse<any[]> = {
  success: true,
  data: [
    {
      name: 'Private Skill 1',
      path: 'private-skill-1/skill.md',
      lastModified: new Date().toISOString(),
    },
    {
      name: 'Private Skill 2',
      path: 'private-skill-2/skill.md',
      lastModified: new Date().toISOString(),
    },
  ],
};

/**
 * Mock Claude directories response
 */
export const mockClaudeDirectoriesResponse: APIResponse<string[]> = {
  success: true,
  data: [
    '/home/test/.claude/skills',
    '/home/test/projects/my-project/.claude/skills',
  ],
};

/**
 * Error responses
 */
export const mockErrorResponse: APIResponse<never> = {
  success: false,
  error: {
    code: 'UNKNOWN_ERROR',
    message: 'An unknown error occurred',
  },
};

export const mockAuthErrorResponse: APIResponse<never> = {
  success: false,
  error: {
    code: 'AUTH_FAILED',
    message: 'Authentication failed. Your PAT may have expired.',
  },
};

export const mockNotFoundResponse: APIResponse<never> = {
  success: false,
  error: {
    code: 'NOT_FOUND',
    message: 'Resource not found',
  },
};

export const mockValidationErrorResponse: APIResponse<never> = {
  success: false,
  error: {
    code: 'VALIDATION_ERROR',
    message: 'Invalid skill name. Only letters, numbers, hyphens, and underscores allowed.',
  },
};

export const mockExternalModificationResponse: APIResponse<never> = {
  success: false,
  error: {
    code: 'EXTERNAL_MODIFICATION',
    message: 'File has been modified externally',
  },
};

/**
 * AI generation responses
 */
export const mockAIStreamChunk = `---
name: AI Generated Skill
description: Generated by Claude
version: 1.0.0
---

# AI Generated Skill

This skill was generated by AI.
`;

/**
 * Search results response
 */
export const mockSearchResultsResponse = {
  results: [
    {
      id: 'skill-1',
      skillId: 'claude-api',
      name: 'Claude API Helper',
      installs: 1000,
      source: 'anthropics/skills',
      description: 'Helper for Claude API',
    },
    {
      id: 'skill-2',
      skillId: 'code-review',
      name: 'Code Review Assistant',
      installs: 500,
      source: 'example/skills',
      description: 'AI-powered code review',
    },
  ],
  total: 2,
  page: 1,
};

/**
 * Create a mock response helper
 */
export function createMockResponse<T>(data: T, success = true): APIResponse<T> {
  return {
    success,
    data,
  };
}

/**
 * Create a mock error response helper
 */
export function createMockErrorResponse(code: string, message: string): APIResponse<never> {
  return {
    success: false,
    error: { code, message },
  };
}
