/**
 * AI API Mock Utilities
 *
 * Provides utilities for mocking AI generation API calls
 */

import { Page } from '@playwright/test';

export interface MockAIOptions {
  failGeneration?: boolean;
  streamingDelay?: number;
  incompleteContent?: boolean;
  invalidFrontmatter?: boolean;
}

/**
 * Generate mock AI content
 */
export function generateMockAIContent(name: string = 'AI Generated Skill'): string {
  return `---
name: ${name}
description: A skill generated by AI for testing
version: 1.0.0
author: AI
---

# ${name}

This skill was generated by AI for testing purposes.

## Features

- Feature 1
- Feature 2

## Usage

\`\`\`
/${name.toLowerCase().replace(/\s+/g, '-')}
\`\`\`
`;
}

/**
 * Mock AI generation API (non-streaming)
 */
export async function mockAIGeneration(
  page: Page,
  options: MockAIOptions = {}
): Promise<void> {
  const { failGeneration = false, incompleteContent = false, invalidFrontmatter = false } = options;

  await page.route('**/api/ai/generate**', async (route) => {
    if (failGeneration) {
      await route.fulfill({
        status: 500,
        contentType: 'application/json',
        body: JSON.stringify({
          success: false,
          error: { code: 'AI_ERROR', message: 'AI generation failed' },
        }),
      });
      return;
    }

    let content: string;

    if (invalidFrontmatter) {
      content = `---
description: Missing name field
version: 1.0.0
---

# Invalid Skill
`;
    } else if (incompleteContent) {
      content = 'Incomplete content without frontmatter';
    } else {
      content = generateMockAIContent();
    }

    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        success: true,
        data: { content },
      }),
    });
  });
}

/**
 * Mock AI streaming API
 */
export async function mockAIStreaming(
  page: Page,
  options: MockAIOptions = {}
): Promise<void> {
  const { streamingDelay = 100, failGeneration = false } = options;

  await page.route('**/api/ai/stream**', async (route) => {
    if (failGeneration) {
      await route.fulfill({
        status: 500,
        contentType: 'application/json',
        body: JSON.stringify({
          success: false,
          error: { code: 'AI_ERROR', message: 'AI generation failed' },
        }),
      });
      return;
    }

    const content = generateMockAIContent();
    const chunks = content.split('\n');

    // Create a readable stream for SSE
    const stream = new ReadableStream({
      async start(controller) {
        for (const chunk of chunks) {
          await new Promise(resolve => setTimeout(resolve, streamingDelay));
          const data = JSON.stringify({ type: 'content', content: chunk + '\n' });
          controller.enqueue(new TextEncoder().encode(`data: ${data}\n\n`));
        }
        // Send completion event
        const completeData = JSON.stringify({ type: 'complete' });
        controller.enqueue(new TextEncoder().encode(`data: ${completeData}\n\n`));
        controller.close();
      },
    });

    await route.fulfill({
      status: 200,
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
      },
      body: stream as any,
    });
  });
}

/**
 * Mock AI connection test
 */
export async function mockAIConnectionTest(
  page: Page,
  success: boolean = true
): Promise<void> {
  await page.route('**/api/ai/test**', async (route) => {
    if (success) {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          success: true,
          data: { message: 'Connection successful' },
        }),
      });
    } else {
      await route.fulfill({
        status: 401,
        contentType: 'application/json',
        body: JSON.stringify({
          success: false,
          error: { code: 'AUTH_ERROR', message: 'Invalid API key' },
        }),
      });
    }
  });
}

/**
 * Mock AI timeout
 */
export async function mockAITimeout(page: Page): Promise<void> {
  await page.route('**/api/ai/**', async (route) => {
    await new Promise(resolve => setTimeout(resolve, 120000)); // 2 minutes timeout
    await route.abort('timedout');
  });
}

/**
 * Mock AI rate limit
 */
export async function mockAIRateLimit(page: Page): Promise<void> {
  await page.route('**/api/ai/**', async (route) => {
    await route.fulfill({
      status: 429,
      contentType: 'application/json',
      body: JSON.stringify({
        success: false,
        error: {
          code: 'RATE_LIMIT',
          message: 'Rate limit exceeded. Please try again later.',
        },
      }),
    });
  });
}

/**
 * Mock AI token usage exceeded
 */
export async function mockAITokenLimit(page: Page): Promise<void> {
  await page.route('**/api/ai/**', async (route) => {
    await route.fulfill({
      status: 402,
      contentType: 'application/json',
      body: JSON.stringify({
        success: false,
        error: {
          code: 'TOKEN_LIMIT',
          message: 'Token usage limit exceeded',
        },
      }),
    });
  });
}

/**
 * Clear all AI mocks
 */
export async function clearAIMocks(page: Page): Promise<void> {
  await page.unroute('**/api/ai/**');
}
